### ISSUE TITLE
Red title bar and status bar with 0.9.0 (dim theme)

### ISSUE THREAD

**Issue by fknop** [Tyriar/vscode-theme-sapphire#15] opened 2019-05-05 12:39 UTC
Since 0.9.0, the title bar and status bar are red. I found multiples instances of color changes in a commit that are responsible.

Commit: https://github.com/Tyriar/vscode-theme-sapphire/commit/923a889ba4f1434230b8e5ffe59f7fba03992fba

`#060a10` was changed to `#060a010` (which I don't think is a valid color) in multiple instances. 

Workaround for now: I changed the values manually in the extension folder and it works as before.

Image:
![image](https://i.imgur.com/I0DfCOn.png)

**Comment by Tyriar** [comment] 2019-05-05 17:31
Hmm, I can't reproduce this but it's likely related to a color conversion I messed up in vscode-theme-generator@0.1.2, I'll fix that up now.

**Comment by Tyriar** [comment] 2019-05-05 17:32
Ok I can repro after reloading.

**Comment by Tyriar** [comment] 2019-05-05 17:41
Should be fixed in 0.9.1, thanks a bunch for the quick report :+1:

**Closed as completed by Tyriar** 2019-05-05 17:41 UTC
Labels: bug
